"""empty message

Revision ID: 512264f62a03
Revises: 50c27bdc32c9
Create Date: 2023-01-12 15:01:10.484540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512264f62a03'
down_revision = '50c27bdc32c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
