"""empty message

Revision ID: 6974a5459bf5
Revises: b251e87907eb
Create Date: 2023-01-17 13:43:31.043210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6974a5459bf5'
down_revision = 'b251e87907eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_comment', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
