"""empty message

Revision ID: c8b28bbc2d64
Revises: c7fb30945ff9
Create Date: 2023-01-12 14:21:57.073663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b28bbc2d64'
down_revision = 'c7fb30945ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    op.create_table('child',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='child_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='child_pkey')
    )
    # ### end Alembic commands ###
